name = "hastheaibubblepoppedyet"
main = "functions/_middleware.js"
compatibility_date = "2025-01-20"

[[d1_databases]]
binding = "DB"
database_name = "bubble-predictions"
database_id = "d61d132f-eabf-4d2d-b839-71bbc1329e32"
